/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoadmapId = IDL.Record({
  'userId' : IDL.Principal,
  'roadmapId' : IDL.Nat,
});
export const Roadmap = IDL.Record({
  'title' : IDL.Text,
  'careerAdvice' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'studyPlan' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteRoadmap' : IDL.Func([RoadmapId], [], []),
  'getAllUserRoadmapIds' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(RoadmapId)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRoadmap' : IDL.Func([RoadmapId], [Roadmap], ['query']),
  'getUserRoadmaps' : IDL.Func([IDL.Principal], [IDL.Vec(Roadmap)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveRoadmap' : IDL.Func([Roadmap], [RoadmapId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoadmapId = IDL.Record({
    'userId' : IDL.Principal,
    'roadmapId' : IDL.Nat,
  });
  const Roadmap = IDL.Record({
    'title' : IDL.Text,
    'careerAdvice' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'studyPlan' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteRoadmap' : IDL.Func([RoadmapId], [], []),
    'getAllUserRoadmapIds' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RoadmapId)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRoadmap' : IDL.Func([RoadmapId], [Roadmap], ['query']),
    'getUserRoadmaps' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Roadmap)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveRoadmap' : IDL.Func([Roadmap], [RoadmapId], []),
  });
};

export const init = ({ IDL }) => { return []; };