/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Roadmap {
  'title' : string,
  'careerAdvice' : [] | [string],
  'content' : string,
  'createdAt' : bigint,
  'studyPlan' : [] | [string],
}
export interface RoadmapId { 'userId' : Principal, 'roadmapId' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteRoadmap' : ActorMethod<[RoadmapId], undefined>,
  'getAllUserRoadmapIds' : ActorMethod<[Principal], Array<RoadmapId>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRoadmap' : ActorMethod<[RoadmapId], Roadmap>,
  'getUserRoadmaps' : ActorMethod<[Principal], Array<Roadmap>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveRoadmap' : ActorMethod<[Roadmap], RoadmapId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];